Controllers/ContratoController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using inmobiliaria_Toloza_Lopez.Models;
using Microsoft.AspNetCore.Authorization;
namespace inmobiliaria_Toloza_Lopez.Controllers;
using Microsoft.AspNetCore.Http;
public class ContratoController : Controller
{
    private readonly ILogger<ContratoController> _logger;
    private readonly RepositorioInquilino _repositorioInquilino;
    private readonly RepositorioInmueble _repositorioInmueble;

    public ContratoController(RepositorioInquilino repositorioInquilino, RepositorioInmueble repositorioInmueble, ILogger<ContratoController> logger)
    {
        _repositorioInquilino = repositorioInquilino;
        _repositorioInmueble = repositorioInmueble;
        _logger = logger;
    }
    [Authorize]
    public IActionResult Index()
    {
        RepositorioContrato repositorioContrato = new RepositorioContrato();

        var request = HttpContext.Request;
        string? fechaFinCalc = null;
        string? fechaInicioCalc = null;
        string? contratoVence = string.IsNullOrEmpty(request.Query["contratoVence"]) ? "0" : request.Query["contratoVence"];
        try
        {

            if (contratoVence == "30" || contratoVence == "60" || contratoVence == "90")
            {
                fechaInicioCalc = DateOnly.FromDateTime(DateTime.Now).ToString("yyyy-MM-dd");
                fechaFinCalc = DateOnly.FromDateTime(DateTime.Now.Date.AddDays(int.Parse(contratoVence))).ToString("yyyy-MM-dd");
            }
            else if (!(string.IsNullOrEmpty(request.Query["fechaInicioPedida"]) && string.IsNullOrEmpty(request.Query["fechaFinPedida"])))
            {
                fechaInicioCalc = DateOnly.ParseExact(request.Query["fechaInicioPedida"], "yyyy-MM-dd").ToString("yyyy-MM-dd");
                fechaFinCalc = DateOnly.ParseExact(request.Query["fechaFinPedida"], "yyyy-MM-dd").ToString("yyyy-MM-dd");
            }
        }
        catch (Exception e)
        {
            Debug.WriteLine("Error al recibir peticion get: " + e.Message);
            return View();
        }
        ViewBag.fechaFinCalc = fechaFinCalc;
        ViewBag.fechaInicioCalc = fechaInicioCalc;
        var contratos = repositorioContrato.GetContratos(fechaInicioCalc, fechaFinCalc);
        return View(contratos);
    }
    [Authorize]
    public IActionResult Create(int id)
    {
        ViewBag.tipoForm = "Nuevo Contrato...";
        ViewBag.controller = "contrato";
        ViewBag.action = "save";
        Inmueble? inmueble = _repositorioInmueble.GetInmueble(id);
        ViewBag.inmueble = inmueble;
        return View("ContratoFormulario");
    }

    [Authorize]
    [HttpPost]
    //public IActionResult Save(IFormCollection form)
    /** save neuvo contrtato **/
    public IActionResult Save(int idInquilino, int idInmueble, DateOnly fechaInicio, DateOnly fechaFin, string montoMes)
    {
        string userId = User.Identity.IsAuthenticated ? ((System.Security.Claims.ClaimsIdentity)User.Identity).FindFirst("userId")?.Value : null;    
        DateOnly fechaHoy = DateOnly.FromDateTime(DateTime.Now);
        if (fechaInicio >= fechaFin)
        {
            TempData["mensaje"] = "<div class=\"alert alert-warning px-5 mt-4\" role=\"alert\">  No pudo Crearse  Contrato. La fecha Fin " + fechaFin + " debe ser mayor que la fecha Inicio " + fechaInicio + " </div>";
            return Redirect(@$"/contrato/create/{idInmueble}");
        }
        if (fechaInicio < fechaHoy)
        {
            TempData["mensaje"] = "<div class=\"alert alert-warning px-5 mt-4\" role=\"alert\">  No pudo Crearse  Contrato. La fecha Inicio no peude ser menor que el dia actual. No se permiten contratos retroactivos  </div>";
            return Redirect(@$"/contrato/create/{idInmueble}");
        }
        Contrato contrato = new Contrato();
        contrato.id_inquilino = idInquilino;
        contrato.id_inmueble = idInmueble;
        contrato.fecha_inicio = fechaInicio;
        contrato.fecha_fin = fechaFin;
        contrato.fecha_efectiva = fechaFin;
        contrato.monto = decimal.Parse(montoMes);
        RepositorioContrato repositorioContrato = new RepositorioContrato();

        try
        {
            if (repositorioContrato.VerifyInmuebleContrato(contrato.fecha_inicio.ToString("yyyy-MM-dd"), contrato.fecha_fin.ToString("yyyy-MM-dd"), contrato.id_inmueble))
            {
                repositorioContrato.Create(contrato,userId);
                TempData["mensaje"] = "<div class=\"alert alert-success px-5 mt-4\" role=\"alert\">  Contrato creado correctamente</div>";
                return Redirect("/contrato");
            }
            else
            {
                ViewBag.errores = "El inmueble ya tiene un contrato activo en la fechas solicitadas";
                Console.WriteLine("El inmueble ya tiene un contrato activo");
                TempData["mensaje"] = "<div class=\"alert alert-warning px-5 mt-4\" role=\"alert\">  No pudo Crearse  Contrato. El inmueble ya tiene un contrato activo entre las fechas " + contrato.fecha_inicio + " - " + contrato.fecha_fin + "</div>";
                return Redirect(@$"/contrato/create/{contrato.id_inmueble}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("Error en VerifyInmuebleContrato: " + ex.Message);
            TempData["mensaje"] = "<div class=\"alert alert-warning px-5 mt-4\" role=\"alert\">  No pudo Completarse la operacion elsistema arrojo el siguiente error: <em>" + ex.Message + "<em></div>";
            return Redirect(@$"/contrato/create/{contrato.id_inmueble}");
        }
    }

    [Authorize]
    /* listado contratos para un inmueble*/
    public IActionResult List(int id)
    {
        RepositorioContrato repositorioContrato = new RepositorioContrato();
        var contratos = repositorioContrato.GetContratosInmueble(id);
        ViewBag.inmueble = id;
        return View("index", contratos);
    }
    /* listado contratos para un propietario*/
    public IActionResult Propietario(int id)
    {
        RepositorioContrato repositorioContrato = new RepositorioContrato();
        var contratos = repositorioContrato.GetContratosPropietario(id);
        ViewBag.propietario = id;
        return View("index", contratos);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]

    public IActionResult Cancel(int id)
    {

        RepositorioContrato repositorioContrato = new RepositorioContrato();
        Contrato contrato = repositorioContrato.GetContrato(id);

        Inmueble inmueble = _repositorioInmueble.GetInmueble(contrato.id_inmueble);
        ViewBag.inmueble = inmueble;
        ViewBag.tipoForm = "Cancelar Contrato...";
        ViewBag.controller = "pago";
        ViewBag.action = "cancel";


        return View("ContratoCancelFormulario", contrato);
    }


    public IActionResult Renew(int id)
    /** Renovacion **/
    {
        ViewBag.tipoForm = "Nuevo Contrato...";
        ViewBag.controller = "contrato";
        ViewBag.action = "save";
        Inmueble? inmueble = _repositorioInmueble.GetInmueble(id);
        ViewBag.inmueble = inmueble;
        return View("ContratoFormulario");
    }
    [Authorize]
    [HttpGet]
    public IActionResult Renovar(int id)
    {
        ViewBag.tipoForm = "Renovar Contrato";
        ViewBag.controller = "contrato";
        ViewBag.action = "renovar";
        ViewBag.btnAction = "Renovar";
        ViewBag.id = id;
        RepositorioContrato repositorioContrato = new RepositorioContrato();
        Contrato contrato = repositorioContrato.GetContrato(id);
        contrato.fecha_inicio = contrato.fecha_fin.AddDays(1);
        contrato.fecha_fin = contrato.fecha_fin.AddMonths((int)contrato.meses_contrato);
        contrato.fecha_efectiva = contrato.fecha_fin;
        return View("ContratoRenovacionFormulario", contrato);
    }
    [Authorize]
    [HttpPost]
    public IActionResult renovar(int idInquilino, int idInmueble, DateOnly fechaInicio, DateOnly fechaFin, string montoMes, int id)
    {
        DateOnly fechaHoy = DateOnly.FromDateTime(DateTime.Now);
        string userId = User.Identity.IsAuthenticated ? ((System.Security.Claims.ClaimsIdentity)User.Identity).FindFirst("userId")?.Value : null;    
        if (fechaInicio >= fechaFin)
        {
            TempData["mensaje"] = "<div class=\"alert alert-warning px-5 mt-4\" role=\"alert\">  No pudo Crearse  Contrato. La fecha Fin " + fechaFin + " debe ser mayor que la fecha Inicio " + fechaInicio + " </div>";
            return Redirect(@$"/contrato/renovar/{id}");
        }
        if (fechaInicio < fechaHoy)
        {
            TempData["mensaje"] = "<div class=\"alert alert-warning px-5 mt-4\" role=\"alert\">  No pudo Crearse  Contrato. La fecha Inicio no peude ser menor que el dia actual. No se permiten contratos retroactivos  </div>";
            return Redirect(@$"/contrato/renovar/{id}");
        }
        Contrato contrato = new Contrato();
        contrato.id_inquilino = idInquilino;
        contrato.id_inmueble = idInmueble;
        contrato.fecha_inicio = fechaInicio;
        contrato.fecha_fin = fechaFin;
        contrato.fecha_efectiva = fechaFin;
        contrato.monto = decimal.Parse(montoMes);
        RepositorioContrato repositorioContrato = new RepositorioContrato();

        try
        {
            if (repositorioContrato.VerifyInmuebleContrato(contrato.fecha_inicio.ToString("yyyy-MM-dd"), contrato.fecha_fin.ToString("yyyy-MM-dd"), contrato.id_inmueble))
            {
                repositorioContrato.Create(contrato,userId);
                TempData["mensaje"] = "<div class=\"alert alert-success px-5 mt-4\" role=\"alert\">  Contrato creado correctamente</div>";
                return Redirect("/contrato");
            }
            else
            {
                ViewBag.errores = "El inmueble ya tiene un contrato activo en la fechas solicitadas";

Controllers/InmuebleController.cs
using Microsoft.AspNetCore.Mvc;
using inmobiliaria_Toloza_Lopez.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
namespace inmobiliaria_Toloza_Lopez.Controllers;
public class InmuebleController : Controller
{
  private readonly RepositorioInmueble _repositorioInmueble;
  private readonly RepositorioTipoInmueble _repositorioTipoInmueble;
  private readonly RepositorioPropietario repositorioPropietario;
  private readonly RepositorioCiudad _repositorioCiudad;
  private readonly RepositorioZona _repositorioZona;

  public InmuebleController(
      RepositorioInmueble repositorioInmueble,
      RepositorioTipoInmueble repositorioTipoInmueble,
      RepositorioPropietario repositorioPropietario,
      RepositorioCiudad repositorioCiudad,
      RepositorioZona repositorioZona
      )
  {
    _repositorioInmueble = repositorioInmueble;
    _repositorioTipoInmueble = repositorioTipoInmueble;
    this.repositorioPropietario = repositorioPropietario;
    _repositorioCiudad = repositorioCiudad;
    _repositorioZona = repositorioZona;
  }
  [Authorize]
  [HttpGet]
  public IActionResult Index(int page = 1, string usoInmueble = "", string precioInmueble = "", string tipoInmueble = "", string ciudadInmueble = "", string zonaInmueble = "", string fechaInicioPedida = "", string fechaFinPedida = "")
  {
      DateOnly hoy= DateOnly.FromDateTime(DateTime.Now);
    fechaInicioPedida = (fechaInicioPedida=="")?  hoy.ToString("yyyy-MM-dd") : fechaInicioPedida;
    fechaFinPedida = (fechaFinPedida=="")?  hoy.AddYears(1).ToString("yyyy-MM-dd") : fechaInicioPedida;
    ViewBag.query = "usoinmueble " + usoInmueble + ", precioinmueble " + precioInmueble + ", tipoinmueble " + tipoInmueble + ", ciudadinmueble " + ciudadInmueble + ", zonainmueble " + zonaInmueble + "fechaInicioPedida" + fechaInicioPedida + "fechaFinPedida" + fechaFinPedida;
    ViewBag.tipoInmuebles = _repositorioTipoInmueble.GetTipoInmuebles();
    ViewBag.ciudades = _repositorioCiudad.ObtenerCiudades();
    ViewBag.zonas = _repositorioZona.ListarZonas();
    int pageSize = 100; // Elementos por pagina
    var totalItems = _repositorioInmueble.GetTotalInmuebles(usoInmueble, precioInmueble, tipoInmueble, ciudadInmueble, zonaInmueble); // Obtener el total de elementos
    var totalPages = (int)Math.Ceiling(totalItems / (double)pageSize); // Calcular el total de páginas
    var inmuebles = _repositorioInmueble.GetInmuebles(page, pageSize, usoInmueble, precioInmueble, tipoInmueble, ciudadInmueble, zonaInmueble, fechaInicioPedida, fechaFinPedida); // Obtener los inmuebles para la página actual aplicando filtros
    ViewBag.paginaActual = page;
    ViewBag.TotalPages = totalPages;
    return View(inmuebles);
  }
  [Authorize]
  [HttpGet]
  // public IActionResult Create()
  // {
  //   ViewBag.tipoInmuebles = _repositorioTipoInmueble.GetTipoInmuebles();
  //   ViewBag.ciudades = _repositorioCiudad.ObtenerCiudades();
  //   ViewBag.zonas = _repositorioZona.ListarZonas();
  //   ViewBag.propietarios = repositorioPropietario.getPropietarios();
  //   ViewBag.tipoForm = "Nuevo Inmueble";
  //   ViewBag.verboForm = "Nuevo";
  //   return View("InmuebleFormulario");
  // }
  public IActionResult Create(int id)
  {
    ViewBag.tipoInmuebles = _repositorioTipoInmueble.GetTipoInmuebles();
    ViewBag.ciudades = _repositorioCiudad.ObtenerCiudades();
    ViewBag.zonas = _repositorioZona.ListarZonas();
    ViewBag.propietarios = repositorioPropietario.getPropietarios();
    ViewBag.tipoForm = "Nuevo Inmueble";
    ViewBag.verboForm = "Nuevo";
    ViewBag.id_propietario = id;
    return View("InmuebleFormulario");
  }
  [Authorize]
  [HttpGet]
  public IActionResult Edit(int id)
  {

    var inmueble = _repositorioInmueble.GetInmueble(id);
    ViewBag.tipoInmuebles = _repositorioTipoInmueble.GetTipoInmuebles();
    ViewBag.ciudades = _repositorioCiudad.ObtenerCiudades();
    ViewBag.zonas = _repositorioZona.ListarZonas();
    ViewBag.propietarios = repositorioPropietario.getPropietarios();
    ViewBag.tipoForm = "Editando Inmueble";
    ViewBag.verboForm = "Update";
    return View("InmuebleFormulario", inmueble);
  }
  [Authorize]
  [HttpPost]
  public IActionResult Nuevo(Inmueble inmueble)
  {
    string userId = User.Identity.IsAuthenticated ? ((System.Security.Claims.ClaimsIdentity)User.Identity).FindFirst("userId")?.Value : null;    
    var rp = _repositorioInmueble;    
    if (ModelState.IsValid)
    {
      rp.GuardarInmueble(inmueble, userId);
      return RedirectToAction("Index");
    }
    return View(inmueble);  
  }
  [Authorize]
  [HttpPost]
  public IActionResult Update(Inmueble inmueble)
  {
    string userId = User.Identity.IsAuthenticated ? ((System.Security.Claims.ClaimsIdentity)User.Identity).FindFirst("userId")?.Value : null;    
    var rp = _repositorioInmueble;
    rp.ActualizarInmueble(inmueble, userId);
    return RedirectToAction("Index");
  }
  [Authorize(Roles = "administrador")]
  public IActionResult Delete(int id)
  {
    string userId = User.Identity.IsAuthenticated ? ((System.Security.Claims.ClaimsIdentity)User.Identity).FindFirst("userId")?.Value : null;    
    var rp = _repositorioInmueble;
    rp.EliminarInmueble(id, userId);
    return RedirectToAction("Index");
  }
[Authorize]
[ActionName("propietario")]
  public IActionResult InmueblesPorPropietario(int id)
  {

  // int pageSize = 10; // Elementos por pagina
    var listaInmuebles = _repositorioInmueble.GetInmuebleByPropietario(id);
    return View("listadoPorPropietario", listaInmuebles);
  }
}

Controllers/PropietarioController.cs
using Microsoft.AspNetCore.Mvc;
using inmobiliaria_Toloza_Lopez.Models;
using Microsoft.AspNetCore.Authorization;
namespace inmobiliaria_Toloza_Lopez.Controllers;

public class PropietarioController : Controller
{
    [Authorize]
    public IActionResult Index()
    {
        RepositorioPropietario rp = new RepositorioPropietario();
        var lista = rp.getPropietarios();
        return View(lista);
    }
    [Authorize]
    [HttpGet]
    public IActionResult Create()
    {
        ViewBag.tipoForm = "Nuevo Propietario";
        ViewBag.verboForm = "Nuevo";
        return View("PropietarioFormulario");
    }
    [Authorize]
    [HttpGet]
    public IActionResult Edit(int id)
    {
        RepositorioPropietario rp = new RepositorioPropietario();
        ViewBag.tipoForm = "Editando Propietario";
        ViewBag.verboForm = "update";
        var propietario = rp.getPropietario(id);
        return View("PropietarioFormulario", propietario);
    }
    [Authorize]
    [HttpPost]
    public IActionResult Nuevo(Propietario propietario)
    {
        RepositorioPropietario rp = new RepositorioPropietario();
        if (ModelState.IsValid)
        {
            rp.GuardarPropietario(propietario);
            return RedirectToAction("Index");
        }
        return View(propietario);
    }
    [Authorize]
    [HttpPost]
    public IActionResult Update(Propietario propietario)
    {
        RepositorioPropietario rp = new RepositorioPropietario();
        rp.ActualizarPropietario(propietario);
        return RedirectToAction("Index");
    }
    [Authorize(Roles = "administrador")]
    public IActionResult Delete(int id)
    {
        RepositorioPropietario rp = new RepositorioPropietario();
        rp.EliminarPropietario(id);
        return RedirectToAction("Index");

    }
}

Views/Usuario/Index.cshtml
@{
    var userName = User?.Identity?.Name;
    var userRol =
    ((System.Security.Claims.ClaimsIdentity)User.Identity).FindFirst(System.Security.Claims.ClaimTypes.Role)?.Value;
    ViewData["Title"] = "Panel de Administración";
}

<h1>@ViewData["Title"]</h1>

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header text-center">
                    <h2>@ViewData["Title"] de: @userName </h2>
                    <p></p>
                </div>
                <div class="card-body">
                    <p>Panel de control:</p>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="card bg-primary text-white mb-4">
                                <div class="card-body">Usuarios</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" asp-controller="Usuario"
                                        asp-action="Listado">Ver detalles</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card bg-warning text-white mb-4">
                                <div class="card-body">Inmuebles</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" asp-controller="Inmueble"
                                        asp-action="Index">Ver detalles</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card bg-success text-white mb-4">
                                <div class="card-body">Propietarios</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" asp-controller="Propietario"
                                        asp-action="Index">Ver
                                        detalles</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="card bg-danger text-white mb-4">
                                <div class="card-body">Pagos</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" asp-controller="Pago"
                                        asp-action="listarPagos">Ver detalles</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card bg-info text-white mb-4">
                                <div class="card-body">Contratos</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" asp-controller="Contrato" asp-action="">Ver detalles</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card bg-success text-white mb-4">
                                <div class="card-body">ABM Tipo inmueble</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" asp-controller="tipoInmueble"
                                        asp-action="Index">Ver
                                        detalles</a>
                                </div>
                            </div>
                        </div>                        
                        <div class="col-md-4">
                            <div class="card bg-dark text-white mb-4">
                                <div class="card-body">Auditoria Contratos</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" asp-controller="contrato" asp-action="auditoria" >Ver detalles</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card bg-dark text-white mb-4">
                                <div class="card-body">Auditoria Pagos</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" asp-controller="pago" asp-action="auditoria" >Ver detalles</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Usuario/Listado.cshtml
@model IEnumerable<Usuario>

@{
    ViewData["Title"] = "Administracion";
}

<div class="container">
    <h2>@ViewData["Title"]</h2>
    <div class="card">
        <div class="card-body">
            <table class="table table-striped table-hover">
                <thead >
                    <tr>
                        <th colspan="7" class="text-right">
    <a asp-controller="Usuario" asp-action="Create" class="btn btn-success"><i class="fa fa-user-plus"></i>Agregar Usuario</a>
</th>
                    </tr>
                    <tr>
                        <th class="text-center">Nombre</th>
                        <th class="text-center">Apellido</th>
                        <th class="text-center">Email</th>
                        <th class="text-center">DNI</th>
                        <th class="text-center">Rol</th>
                        <th class="text-center">Activo</th>
                        <th class="text-center">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var usuario in Model)
                    {
                        <tr>
                            <td class="text-center">@usuario.nombre</td>
                            <td class="text-center">@usuario.apellido</td>
                            <td class="text-center">@usuario.email</td>
                            <td class="text-center">@usuario.dni</td>
                            <td class="text-center">@usuario.rol</td>
                            <td class="text-center">
                                <div class="form-group">
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" class="custom-control-input usuario-switch" id="borrado-@usuario.id"
                                            name="borrado" value="true" @(usuario.borrado == false ? "checked" : "") disabled />
                                        <label class="custom-control-label" for="borrado-@usuario.id">@(usuario.borrado ==
                                        false ? "Activo" : "Inactivo")</label>
                                    </div>
                                </div>
                            </td>
                            <td class="text-center">
                                <a asp-controller="Usuario" asp-action="PerfilUsuario" asp-route-id=@usuario.id class="btn btn-primary"
                                    aria-label="Editar usuario @usuario.nombre">Editar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.usuario-switch').change(function () {
                if (this.checked) {
                    $(this).next('label').text('Activo');
                } else {
                    $(this).next('label').text('Inactivo');
                }
            });
        });
    </script>
}

Views/Usuario/UsuarioFormulario.cshtml
@model inmobiliaria_Toloza_Lopez.Models.Usuario

@{
    ViewData["Title"] = "Agregar Usuario";
}

<div class="container w-75 m-5">
    <div class="text-center">
        <h1 class="display-3">@ViewData["Title"]</h1>
    </div>
    <form method="POST" id="formularioUsuario" asp-action="Create" asp-controller="Usuario"
        enctype="multipart/form-data">
        <div class="w-100 m-5">
            <div class="w-75 m-5">
                <label for="nombre-usuario" class="">Nombre</label>
                <input type="text" class="form-control" id="nombre-usuario" placeholder="Ingrese nombre" name="nombre"
                    required>
            </div>
            <div class="w-75 m-5">
                <label for="apellido-usuario" class="">Apellido</label>
                <input type="text" class="form-control" id="apellido-usuario" placeholder="Ingrese apellido"
                    name="apellido" required>
            </div>
            <div class="w-75 m-5">
                <label for="email-usuario" class="">Email</label>
                <input type="email" class="form-control" id="email-usuario" placeholder="Ingrese email" name="email"
                    required>
            </div>
            <div class="w-75 m-5">
                <label for="dni-usuario" class="">DNI</label>
                <input type="text" class="form-control" id="dni-usuario" placeholder="Ingrese DNI" name="dni" required>
            </div>
            <div class="w-75 m-5">
                <label for="rol-usuario" class="">Rol</label>
                <select class="form-select" id="rol-usuario" name="rol" required>
                    <option value="">Seleccione el rol</option>
                    <option value="administrador">Administrador</option>
                    <option value="usuario">Usuario</option>
                </select>
            </div>
            <div class="w-75 m-5">
                <label for="password" class="">Contraseña</label>
                <input type="password" class="form-control" id="password" placeholder="Ingrese contraseña"
                    name="password" required>
            </div>
            <div class="w-75 m-5">
                <label for="passConfirm" class="">Repita su contraseña</label>
                <input type="password" class="form-control" id="passConfirm" placeholder="Ingrese contraseña"
                    name="passwordConfirm" required>
            </div>
            <div class="w-75 m-5">
                <label for="image">Imagen de perfil:</label>
                <input type="file" id="image" name="avatarFile" class="form-control" accept="image/*">
            </div>
            <div class="d-flex flex-column justify-content-end align-items-end">
                <button id="btnEnviar" type="submit" class="btn btn-primary" onclick="alerta()" disabled>Crear
                    Usuario</button>
            </div>

        </div>
    </form>
</div>

@section Scripts {
    <script src="~/js/propietario.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        const formUsuario = document.getElementById("formularioUsuario");
        const pass = document.getElementById("password");
        const passConfirm = document.getElementById("passConfirm");
        const btnEnviar = document.getElementById("btnEnviar");
        btnEnviar.disabled = true;
        function alerta(event) {
            event.preventDefault();
            Swal.fire({
                title: 'Atención!',
                text: 'Está por crear un nuevo usuario',
                icon: 'question',
                showCloseButton: true,
                showCancelButton: true
            }).then((result) => {
                if (result.isConfirmed) {
                    Swal.fire("Creando", "", "success");
                    formUsuario.submit();
                }
            });
        }
        formUsuario.addEventListener('input', function () {
            if (formUsuario.checkValidity()) {
                btnEnviar.disabled = false;
            } else {
                btnEnviar.disabled = true;
            }
        });
        btnEnviar.addEventListener('click', function (event) {
            alerta(event);
        });
        formUsuario.addEventListener('submit', function (event) {
            event.preventDefault();
            if (pass.value !== passConfirm.value) {
                Swal.fire({
                    title: 'Atención!',
                    text: 'Las contraseñas no coinciden',
                    icon: 'question',
                    showCloseButton: true,
                    showCancelButton: true
                });
            } else {
                alerta(event);
            }
        });
    </script>
}